// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/keyfile.proto

package com.google.cloud.gszutil;

public final class KeyFileProto {
  private KeyFileProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface KeyFileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:google.protobuf.KeyFile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string type = 1;</code>
     */
    java.lang.String getType();
    /**
     * <code>string type = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>string project_id = 2;</code>
     */
    java.lang.String getProjectId();
    /**
     * <code>string project_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getProjectIdBytes();

    /**
     * <code>string private_key_id = 3;</code>
     */
    java.lang.String getPrivateKeyId();
    /**
     * <code>string private_key_id = 3;</code>
     */
    com.google.protobuf.ByteString
        getPrivateKeyIdBytes();

    /**
     * <code>string private_key = 4;</code>
     */
    java.lang.String getPrivateKey();
    /**
     * <code>string private_key = 4;</code>
     */
    com.google.protobuf.ByteString
        getPrivateKeyBytes();

    /**
     * <code>string client_email = 5;</code>
     */
    java.lang.String getClientEmail();
    /**
     * <code>string client_email = 5;</code>
     */
    com.google.protobuf.ByteString
        getClientEmailBytes();

    /**
     * <code>string client_id = 6;</code>
     */
    java.lang.String getClientId();
    /**
     * <code>string client_id = 6;</code>
     */
    com.google.protobuf.ByteString
        getClientIdBytes();

    /**
     * <code>string auth_uri = 7;</code>
     */
    java.lang.String getAuthUri();
    /**
     * <code>string auth_uri = 7;</code>
     */
    com.google.protobuf.ByteString
        getAuthUriBytes();

    /**
     * <code>string token_uri = 8;</code>
     */
    java.lang.String getTokenUri();
    /**
     * <code>string token_uri = 8;</code>
     */
    com.google.protobuf.ByteString
        getTokenUriBytes();

    /**
     * <code>string auth_provider_x509_cert_url = 9;</code>
     */
    java.lang.String getAuthProviderX509CertUrl();
    /**
     * <code>string auth_provider_x509_cert_url = 9;</code>
     */
    com.google.protobuf.ByteString
        getAuthProviderX509CertUrlBytes();

    /**
     * <code>string client_x509_cert_url = 10;</code>
     */
    java.lang.String getClientX509CertUrl();
    /**
     * <code>string client_x509_cert_url = 10;</code>
     */
    com.google.protobuf.ByteString
        getClientX509CertUrlBytes();

    /**
     * <code>string access_token = 11;</code>
     */
    java.lang.String getAccessToken();
    /**
     * <code>string access_token = 11;</code>
     */
    com.google.protobuf.ByteString
        getAccessTokenBytes();
  }
  /**
   * Protobuf type {@code google.protobuf.KeyFile}
   */
  public  static final class KeyFile extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:google.protobuf.KeyFile)
      KeyFileOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use KeyFile.newBuilder() to construct.
    private KeyFile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private KeyFile() {
      type_ = "";
      projectId_ = "";
      privateKeyId_ = "";
      privateKey_ = "";
      clientEmail_ = "";
      clientId_ = "";
      authUri_ = "";
      tokenUri_ = "";
      authProviderX509CertUrl_ = "";
      clientX509CertUrl_ = "";
      accessToken_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private KeyFile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              projectId_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              privateKeyId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              privateKey_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              clientEmail_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              clientId_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              authUri_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              tokenUri_ = s;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              authProviderX509CertUrl_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              clientX509CertUrl_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              accessToken_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.cloud.gszutil.KeyFileProto.internal_static_google_protobuf_KeyFile_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.gszutil.KeyFileProto.internal_static_google_protobuf_KeyFile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.gszutil.KeyFileProto.KeyFile.class, com.google.cloud.gszutil.KeyFileProto.KeyFile.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object type_;
    /**
     * <code>string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROJECT_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object projectId_;
    /**
     * <code>string project_id = 2;</code>
     */
    public java.lang.String getProjectId() {
      java.lang.Object ref = projectId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        projectId_ = s;
        return s;
      }
    }
    /**
     * <code>string project_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProjectIdBytes() {
      java.lang.Object ref = projectId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        projectId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRIVATE_KEY_ID_FIELD_NUMBER = 3;
    private volatile java.lang.Object privateKeyId_;
    /**
     * <code>string private_key_id = 3;</code>
     */
    public java.lang.String getPrivateKeyId() {
      java.lang.Object ref = privateKeyId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        privateKeyId_ = s;
        return s;
      }
    }
    /**
     * <code>string private_key_id = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPrivateKeyIdBytes() {
      java.lang.Object ref = privateKeyId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        privateKeyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRIVATE_KEY_FIELD_NUMBER = 4;
    private volatile java.lang.Object privateKey_;
    /**
     * <code>string private_key = 4;</code>
     */
    public java.lang.String getPrivateKey() {
      java.lang.Object ref = privateKey_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        privateKey_ = s;
        return s;
      }
    }
    /**
     * <code>string private_key = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPrivateKeyBytes() {
      java.lang.Object ref = privateKey_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        privateKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENT_EMAIL_FIELD_NUMBER = 5;
    private volatile java.lang.Object clientEmail_;
    /**
     * <code>string client_email = 5;</code>
     */
    public java.lang.String getClientEmail() {
      java.lang.Object ref = clientEmail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientEmail_ = s;
        return s;
      }
    }
    /**
     * <code>string client_email = 5;</code>
     */
    public com.google.protobuf.ByteString
        getClientEmailBytes() {
      java.lang.Object ref = clientEmail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENT_ID_FIELD_NUMBER = 6;
    private volatile java.lang.Object clientId_;
    /**
     * <code>string client_id = 6;</code>
     */
    public java.lang.String getClientId() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientId_ = s;
        return s;
      }
    }
    /**
     * <code>string client_id = 6;</code>
     */
    public com.google.protobuf.ByteString
        getClientIdBytes() {
      java.lang.Object ref = clientId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTH_URI_FIELD_NUMBER = 7;
    private volatile java.lang.Object authUri_;
    /**
     * <code>string auth_uri = 7;</code>
     */
    public java.lang.String getAuthUri() {
      java.lang.Object ref = authUri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authUri_ = s;
        return s;
      }
    }
    /**
     * <code>string auth_uri = 7;</code>
     */
    public com.google.protobuf.ByteString
        getAuthUriBytes() {
      java.lang.Object ref = authUri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_URI_FIELD_NUMBER = 8;
    private volatile java.lang.Object tokenUri_;
    /**
     * <code>string token_uri = 8;</code>
     */
    public java.lang.String getTokenUri() {
      java.lang.Object ref = tokenUri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tokenUri_ = s;
        return s;
      }
    }
    /**
     * <code>string token_uri = 8;</code>
     */
    public com.google.protobuf.ByteString
        getTokenUriBytes() {
      java.lang.Object ref = tokenUri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tokenUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AUTH_PROVIDER_X509_CERT_URL_FIELD_NUMBER = 9;
    private volatile java.lang.Object authProviderX509CertUrl_;
    /**
     * <code>string auth_provider_x509_cert_url = 9;</code>
     */
    public java.lang.String getAuthProviderX509CertUrl() {
      java.lang.Object ref = authProviderX509CertUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authProviderX509CertUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string auth_provider_x509_cert_url = 9;</code>
     */
    public com.google.protobuf.ByteString
        getAuthProviderX509CertUrlBytes() {
      java.lang.Object ref = authProviderX509CertUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authProviderX509CertUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENT_X509_CERT_URL_FIELD_NUMBER = 10;
    private volatile java.lang.Object clientX509CertUrl_;
    /**
     * <code>string client_x509_cert_url = 10;</code>
     */
    public java.lang.String getClientX509CertUrl() {
      java.lang.Object ref = clientX509CertUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientX509CertUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string client_x509_cert_url = 10;</code>
     */
    public com.google.protobuf.ByteString
        getClientX509CertUrlBytes() {
      java.lang.Object ref = clientX509CertUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientX509CertUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCESS_TOKEN_FIELD_NUMBER = 11;
    private volatile java.lang.Object accessToken_;
    /**
     * <code>string access_token = 11;</code>
     */
    public java.lang.String getAccessToken() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accessToken_ = s;
        return s;
      }
    }
    /**
     * <code>string access_token = 11;</code>
     */
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (!getProjectIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, projectId_);
      }
      if (!getPrivateKeyIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, privateKeyId_);
      }
      if (!getPrivateKeyBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, privateKey_);
      }
      if (!getClientEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, clientEmail_);
      }
      if (!getClientIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, clientId_);
      }
      if (!getAuthUriBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, authUri_);
      }
      if (!getTokenUriBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, tokenUri_);
      }
      if (!getAuthProviderX509CertUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, authProviderX509CertUrl_);
      }
      if (!getClientX509CertUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, clientX509CertUrl_);
      }
      if (!getAccessTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, accessToken_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (!getProjectIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, projectId_);
      }
      if (!getPrivateKeyIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, privateKeyId_);
      }
      if (!getPrivateKeyBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, privateKey_);
      }
      if (!getClientEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, clientEmail_);
      }
      if (!getClientIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, clientId_);
      }
      if (!getAuthUriBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, authUri_);
      }
      if (!getTokenUriBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, tokenUri_);
      }
      if (!getAuthProviderX509CertUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, authProviderX509CertUrl_);
      }
      if (!getClientX509CertUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, clientX509CertUrl_);
      }
      if (!getAccessTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, accessToken_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.cloud.gszutil.KeyFileProto.KeyFile)) {
        return super.equals(obj);
      }
      com.google.cloud.gszutil.KeyFileProto.KeyFile other = (com.google.cloud.gszutil.KeyFileProto.KeyFile) obj;

      boolean result = true;
      result = result && getType()
          .equals(other.getType());
      result = result && getProjectId()
          .equals(other.getProjectId());
      result = result && getPrivateKeyId()
          .equals(other.getPrivateKeyId());
      result = result && getPrivateKey()
          .equals(other.getPrivateKey());
      result = result && getClientEmail()
          .equals(other.getClientEmail());
      result = result && getClientId()
          .equals(other.getClientId());
      result = result && getAuthUri()
          .equals(other.getAuthUri());
      result = result && getTokenUri()
          .equals(other.getTokenUri());
      result = result && getAuthProviderX509CertUrl()
          .equals(other.getAuthProviderX509CertUrl());
      result = result && getClientX509CertUrl()
          .equals(other.getClientX509CertUrl());
      result = result && getAccessToken()
          .equals(other.getAccessToken());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + PROJECT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getProjectId().hashCode();
      hash = (37 * hash) + PRIVATE_KEY_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPrivateKeyId().hashCode();
      hash = (37 * hash) + PRIVATE_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getPrivateKey().hashCode();
      hash = (37 * hash) + CLIENT_EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getClientEmail().hashCode();
      hash = (37 * hash) + CLIENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getClientId().hashCode();
      hash = (37 * hash) + AUTH_URI_FIELD_NUMBER;
      hash = (53 * hash) + getAuthUri().hashCode();
      hash = (37 * hash) + TOKEN_URI_FIELD_NUMBER;
      hash = (53 * hash) + getTokenUri().hashCode();
      hash = (37 * hash) + AUTH_PROVIDER_X509_CERT_URL_FIELD_NUMBER;
      hash = (53 * hash) + getAuthProviderX509CertUrl().hashCode();
      hash = (37 * hash) + CLIENT_X509_CERT_URL_FIELD_NUMBER;
      hash = (53 * hash) + getClientX509CertUrl().hashCode();
      hash = (37 * hash) + ACCESS_TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getAccessToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.cloud.gszutil.KeyFileProto.KeyFile parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.cloud.gszutil.KeyFileProto.KeyFile parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.cloud.gszutil.KeyFileProto.KeyFile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.cloud.gszutil.KeyFileProto.KeyFile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.cloud.gszutil.KeyFileProto.KeyFile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.cloud.gszutil.KeyFileProto.KeyFile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.cloud.gszutil.KeyFileProto.KeyFile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.cloud.gszutil.KeyFileProto.KeyFile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.cloud.gszutil.KeyFileProto.KeyFile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.google.cloud.gszutil.KeyFileProto.KeyFile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.cloud.gszutil.KeyFileProto.KeyFile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.google.cloud.gszutil.KeyFileProto.KeyFile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.cloud.gszutil.KeyFileProto.KeyFile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code google.protobuf.KeyFile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:google.protobuf.KeyFile)
        com.google.cloud.gszutil.KeyFileProto.KeyFileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.cloud.gszutil.KeyFileProto.internal_static_google_protobuf_KeyFile_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.cloud.gszutil.KeyFileProto.internal_static_google_protobuf_KeyFile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.cloud.gszutil.KeyFileProto.KeyFile.class, com.google.cloud.gszutil.KeyFileProto.KeyFile.Builder.class);
      }

      // Construct using com.google.cloud.gszutil.KeyFileProto.KeyFile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        type_ = "";

        projectId_ = "";

        privateKeyId_ = "";

        privateKey_ = "";

        clientEmail_ = "";

        clientId_ = "";

        authUri_ = "";

        tokenUri_ = "";

        authProviderX509CertUrl_ = "";

        clientX509CertUrl_ = "";

        accessToken_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.cloud.gszutil.KeyFileProto.internal_static_google_protobuf_KeyFile_descriptor;
      }

      @java.lang.Override
      public com.google.cloud.gszutil.KeyFileProto.KeyFile getDefaultInstanceForType() {
        return com.google.cloud.gszutil.KeyFileProto.KeyFile.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.cloud.gszutil.KeyFileProto.KeyFile build() {
        com.google.cloud.gszutil.KeyFileProto.KeyFile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.cloud.gszutil.KeyFileProto.KeyFile buildPartial() {
        com.google.cloud.gszutil.KeyFileProto.KeyFile result = new com.google.cloud.gszutil.KeyFileProto.KeyFile(this);
        result.type_ = type_;
        result.projectId_ = projectId_;
        result.privateKeyId_ = privateKeyId_;
        result.privateKey_ = privateKey_;
        result.clientEmail_ = clientEmail_;
        result.clientId_ = clientId_;
        result.authUri_ = authUri_;
        result.tokenUri_ = tokenUri_;
        result.authProviderX509CertUrl_ = authProviderX509CertUrl_;
        result.clientX509CertUrl_ = clientX509CertUrl_;
        result.accessToken_ = accessToken_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.cloud.gszutil.KeyFileProto.KeyFile) {
          return mergeFrom((com.google.cloud.gszutil.KeyFileProto.KeyFile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.cloud.gszutil.KeyFileProto.KeyFile other) {
        if (other == com.google.cloud.gszutil.KeyFileProto.KeyFile.getDefaultInstance()) return this;
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (!other.getProjectId().isEmpty()) {
          projectId_ = other.projectId_;
          onChanged();
        }
        if (!other.getPrivateKeyId().isEmpty()) {
          privateKeyId_ = other.privateKeyId_;
          onChanged();
        }
        if (!other.getPrivateKey().isEmpty()) {
          privateKey_ = other.privateKey_;
          onChanged();
        }
        if (!other.getClientEmail().isEmpty()) {
          clientEmail_ = other.clientEmail_;
          onChanged();
        }
        if (!other.getClientId().isEmpty()) {
          clientId_ = other.clientId_;
          onChanged();
        }
        if (!other.getAuthUri().isEmpty()) {
          authUri_ = other.authUri_;
          onChanged();
        }
        if (!other.getTokenUri().isEmpty()) {
          tokenUri_ = other.tokenUri_;
          onChanged();
        }
        if (!other.getAuthProviderX509CertUrl().isEmpty()) {
          authProviderX509CertUrl_ = other.authProviderX509CertUrl_;
          onChanged();
        }
        if (!other.getClientX509CertUrl().isEmpty()) {
          clientX509CertUrl_ = other.clientX509CertUrl_;
          onChanged();
        }
        if (!other.getAccessToken().isEmpty()) {
          accessToken_ = other.accessToken_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.cloud.gszutil.KeyFileProto.KeyFile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.google.cloud.gszutil.KeyFileProto.KeyFile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <code>string type = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 1;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object projectId_ = "";
      /**
       * <code>string project_id = 2;</code>
       */
      public java.lang.String getProjectId() {
        java.lang.Object ref = projectId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          projectId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string project_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getProjectIdBytes() {
        java.lang.Object ref = projectId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          projectId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string project_id = 2;</code>
       */
      public Builder setProjectId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        projectId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string project_id = 2;</code>
       */
      public Builder clearProjectId() {
        
        projectId_ = getDefaultInstance().getProjectId();
        onChanged();
        return this;
      }
      /**
       * <code>string project_id = 2;</code>
       */
      public Builder setProjectIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        projectId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object privateKeyId_ = "";
      /**
       * <code>string private_key_id = 3;</code>
       */
      public java.lang.String getPrivateKeyId() {
        java.lang.Object ref = privateKeyId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          privateKeyId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string private_key_id = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPrivateKeyIdBytes() {
        java.lang.Object ref = privateKeyId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          privateKeyId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string private_key_id = 3;</code>
       */
      public Builder setPrivateKeyId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        privateKeyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string private_key_id = 3;</code>
       */
      public Builder clearPrivateKeyId() {
        
        privateKeyId_ = getDefaultInstance().getPrivateKeyId();
        onChanged();
        return this;
      }
      /**
       * <code>string private_key_id = 3;</code>
       */
      public Builder setPrivateKeyIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        privateKeyId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object privateKey_ = "";
      /**
       * <code>string private_key = 4;</code>
       */
      public java.lang.String getPrivateKey() {
        java.lang.Object ref = privateKey_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          privateKey_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string private_key = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPrivateKeyBytes() {
        java.lang.Object ref = privateKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          privateKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string private_key = 4;</code>
       */
      public Builder setPrivateKey(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        privateKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string private_key = 4;</code>
       */
      public Builder clearPrivateKey() {
        
        privateKey_ = getDefaultInstance().getPrivateKey();
        onChanged();
        return this;
      }
      /**
       * <code>string private_key = 4;</code>
       */
      public Builder setPrivateKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        privateKey_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientEmail_ = "";
      /**
       * <code>string client_email = 5;</code>
       */
      public java.lang.String getClientEmail() {
        java.lang.Object ref = clientEmail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientEmail_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string client_email = 5;</code>
       */
      public com.google.protobuf.ByteString
          getClientEmailBytes() {
        java.lang.Object ref = clientEmail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientEmail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string client_email = 5;</code>
       */
      public Builder setClientEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientEmail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string client_email = 5;</code>
       */
      public Builder clearClientEmail() {
        
        clientEmail_ = getDefaultInstance().getClientEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string client_email = 5;</code>
       */
      public Builder setClientEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientEmail_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientId_ = "";
      /**
       * <code>string client_id = 6;</code>
       */
      public java.lang.String getClientId() {
        java.lang.Object ref = clientId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string client_id = 6;</code>
       */
      public com.google.protobuf.ByteString
          getClientIdBytes() {
        java.lang.Object ref = clientId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string client_id = 6;</code>
       */
      public Builder setClientId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string client_id = 6;</code>
       */
      public Builder clearClientId() {
        
        clientId_ = getDefaultInstance().getClientId();
        onChanged();
        return this;
      }
      /**
       * <code>string client_id = 6;</code>
       */
      public Builder setClientIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object authUri_ = "";
      /**
       * <code>string auth_uri = 7;</code>
       */
      public java.lang.String getAuthUri() {
        java.lang.Object ref = authUri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          authUri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string auth_uri = 7;</code>
       */
      public com.google.protobuf.ByteString
          getAuthUriBytes() {
        java.lang.Object ref = authUri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authUri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string auth_uri = 7;</code>
       */
      public Builder setAuthUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        authUri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string auth_uri = 7;</code>
       */
      public Builder clearAuthUri() {
        
        authUri_ = getDefaultInstance().getAuthUri();
        onChanged();
        return this;
      }
      /**
       * <code>string auth_uri = 7;</code>
       */
      public Builder setAuthUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        authUri_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object tokenUri_ = "";
      /**
       * <code>string token_uri = 8;</code>
       */
      public java.lang.String getTokenUri() {
        java.lang.Object ref = tokenUri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tokenUri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string token_uri = 8;</code>
       */
      public com.google.protobuf.ByteString
          getTokenUriBytes() {
        java.lang.Object ref = tokenUri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tokenUri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string token_uri = 8;</code>
       */
      public Builder setTokenUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tokenUri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string token_uri = 8;</code>
       */
      public Builder clearTokenUri() {
        
        tokenUri_ = getDefaultInstance().getTokenUri();
        onChanged();
        return this;
      }
      /**
       * <code>string token_uri = 8;</code>
       */
      public Builder setTokenUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tokenUri_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object authProviderX509CertUrl_ = "";
      /**
       * <code>string auth_provider_x509_cert_url = 9;</code>
       */
      public java.lang.String getAuthProviderX509CertUrl() {
        java.lang.Object ref = authProviderX509CertUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          authProviderX509CertUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string auth_provider_x509_cert_url = 9;</code>
       */
      public com.google.protobuf.ByteString
          getAuthProviderX509CertUrlBytes() {
        java.lang.Object ref = authProviderX509CertUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          authProviderX509CertUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string auth_provider_x509_cert_url = 9;</code>
       */
      public Builder setAuthProviderX509CertUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        authProviderX509CertUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string auth_provider_x509_cert_url = 9;</code>
       */
      public Builder clearAuthProviderX509CertUrl() {
        
        authProviderX509CertUrl_ = getDefaultInstance().getAuthProviderX509CertUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string auth_provider_x509_cert_url = 9;</code>
       */
      public Builder setAuthProviderX509CertUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        authProviderX509CertUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientX509CertUrl_ = "";
      /**
       * <code>string client_x509_cert_url = 10;</code>
       */
      public java.lang.String getClientX509CertUrl() {
        java.lang.Object ref = clientX509CertUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientX509CertUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string client_x509_cert_url = 10;</code>
       */
      public com.google.protobuf.ByteString
          getClientX509CertUrlBytes() {
        java.lang.Object ref = clientX509CertUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientX509CertUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string client_x509_cert_url = 10;</code>
       */
      public Builder setClientX509CertUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientX509CertUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string client_x509_cert_url = 10;</code>
       */
      public Builder clearClientX509CertUrl() {
        
        clientX509CertUrl_ = getDefaultInstance().getClientX509CertUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string client_x509_cert_url = 10;</code>
       */
      public Builder setClientX509CertUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientX509CertUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object accessToken_ = "";
      /**
       * <code>string access_token = 11;</code>
       */
      public java.lang.String getAccessToken() {
        java.lang.Object ref = accessToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accessToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string access_token = 11;</code>
       */
      public com.google.protobuf.ByteString
          getAccessTokenBytes() {
        java.lang.Object ref = accessToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accessToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string access_token = 11;</code>
       */
      public Builder setAccessToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accessToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string access_token = 11;</code>
       */
      public Builder clearAccessToken() {
        
        accessToken_ = getDefaultInstance().getAccessToken();
        onChanged();
        return this;
      }
      /**
       * <code>string access_token = 11;</code>
       */
      public Builder setAccessTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accessToken_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:google.protobuf.KeyFile)
    }

    // @@protoc_insertion_point(class_scope:google.protobuf.KeyFile)
    private static final com.google.cloud.gszutil.KeyFileProto.KeyFile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.cloud.gszutil.KeyFileProto.KeyFile();
    }

    public static com.google.cloud.gszutil.KeyFileProto.KeyFile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<KeyFile>
        PARSER = new com.google.protobuf.AbstractParser<KeyFile>() {
      @java.lang.Override
      public KeyFile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new KeyFile(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<KeyFile> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<KeyFile> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.cloud.gszutil.KeyFileProto.KeyFile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_KeyFile_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_KeyFile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto/keyfile.proto\022\017google.protobuf\"\377" +
      "\001\n\007KeyFile\022\014\n\004type\030\001 \001(\t\022\022\n\nproject_id\030\002" +
      " \001(\t\022\026\n\016private_key_id\030\003 \001(\t\022\023\n\013private_" +
      "key\030\004 \001(\t\022\024\n\014client_email\030\005 \001(\t\022\021\n\tclien" +
      "t_id\030\006 \001(\t\022\020\n\010auth_uri\030\007 \001(\t\022\021\n\ttoken_ur" +
      "i\030\010 \001(\t\022#\n\033auth_provider_x509_cert_url\030\t" +
      " \001(\t\022\034\n\024client_x509_cert_url\030\n \001(\t\022\024\n\014ac" +
      "cess_token\030\013 \001(\tB(\n\030com.google.cloud.gsz" +
      "utilB\014KeyFileProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_google_protobuf_KeyFile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_protobuf_KeyFile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_KeyFile_descriptor,
        new java.lang.String[] { "Type", "ProjectId", "PrivateKeyId", "PrivateKey", "ClientEmail", "ClientId", "AuthUri", "TokenUri", "AuthProviderX509CertUrl", "ClientX509CertUrl", "AccessToken", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
